---
- name: Detect docker container
  stat:
    path: "/.dockerenv"
  register: dockerenv
- name: Make sure that needed packages are installed
  apt:
    name:
      - apache2
      - cron
      - curl
      - git
      - moreutils
    state: present
- name: Make sure that apache is started
  service:
    name: apache2
    state: started

- name: Clone / update dehydrated script for letsencrypt
  git:
    repo: https://github.com/dehydrated-io/dehydrated
    dest: /root/dehydrated
    version: "{{ letsencrypt_dehydrated_version }}"
- name: Create letsencrypt directory
  file: path=/etc/ssl/letsencrypt state=directory owner=root group=root mode=0755

- name: Deploy dehydrated config file
  template:
    src: 'etc_ssl_letsencrypt/config.j2'
    dest: '/etc/ssl/letsencrypt/config'
    owner: root
    group: root
    mode: 0644

- name: Deploy dehydrated domains
  template: src=etc_ssl_letsencrypt/domains.txt.j2 dest=/etc/ssl/letsencrypt/domains.txt owner=root group=root mode=0644
- name: Setup http-01-type verification for letsencrypt
  file: path=/var/www/dehydrated state=directory owner=root group=root mode=0755

- name: Check for /etc/apache2/conf.d (used by Debian 8 and below)
  stat: path=/etc/apache2/conf.d
  register: confd
- name: Deploy Apache configuration for letsencrypt to conf.d
  copy: src=etc_apache2_conf-available/letsencrypt.conf dest=/etc/apache2/conf.d/letsencrypt.conf owner=root group=root mode=0644
  when: confd.stat.exists
  notify:
    - reload apache2

- name: Deploy Apache configuration for letsencrypt to conf-available
  copy: src=etc_apache2_conf-available/letsencrypt.conf dest=/etc/apache2/conf-available/letsencrypt.conf owner=root group=root mode=0644
  when: not confd.stat.exists
- name: Enable Apache / letsencrypt configuration
  file: src=../conf-available/letsencrypt.conf dest=/etc/apache2/conf-enabled/letsencrypt.conf state=link
  when: not confd.stat.exists and not ansible_check_mode
  notify:
    - reload apache2

- meta: flush_handlers

- name: Run dehydrated (register account key)
  command: /root/dehydrated/dehydrated --config /etc/ssl/letsencrypt/config --register --accept-terms
  register: dehydrated_register
  changed_when: "'+ Account already registered!' not in dehydrated_register.stdout"
  # Let's Encrypt client / dehydrated should not register account key in molecule test
  when: not dockerenv.stat.exists
  notify:
    - restart apache2
- name: Run dehydrated (sign/renew keys)
  command: /root/dehydrated/dehydrated --config /etc/ssl/letsencrypt/config -c
  register: dehydrated_config
  changed_when: "'Skipping renew!' not in dehydrated_config.stdout"
  # Let's Encrypt client / dehydrated should not sign/renew keys when in molecule test
  when: not dockerenv.stat.exists
  notify:
    - restart apache2
- name: Enable cronjob for dehydrated
  copy: src=files/cron.d/letsencrypt dest=/etc/cron.d/letsencrypt owner=root group=root mode=0644
